# Generated by Django 5.2.1 on 2025-05-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_generator", "0002_holiday_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtworkOverlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="artwork/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="holiday",
            name="artwork",
            field=models.ForeignKey(
                blank=True,
                help_text="Artwork overlay to use for this holiday",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="calendar_generator.artworkoverlay",
            ),
        ),
    ]
